// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(server) {
    var adminBasePath, adminHttp, cAdminApp;
    cAdminApp = server.express();
    cAdminApp.use(server.bodyParser.urlencoded({
      extended: true
    }));
    adminBasePath = server.path.normalize(server.config.appFolder + '/../../admin');
    cAdminApp.use(server.express["static"](adminBasePath + '/public'));
    cAdminApp.set('view engine', 'ejs');
    cAdminApp.set('views', adminBasePath + '/views');
    cAdminApp.engine('html', require('ejs').renderFile);
    cAdminApp.get('/auth', (function(req, res) {
      return res.render('auth.html', {
        error: null
      });
    }).bind(this));
    cAdminApp.post('/auth', (function(req, res) {
      if (!req.body.password) {
        res.render('auth.html', {
          error: 'Password required'
        });
        return;
      }
      if (req.body.password !== server.config.adminPassword) {
        res.render('auth.html', {
          error: 'Password required'
        });
        return;
      }
      return res.redirect('/');
    }).bind(this));
    cAdminApp.get('/', (function(req, res) {
      return res.render('index.html', {
        apiUri: server.config.host + ':' + server.config.port,
        adminPassword: server.config.adminPassword
      });
    }));
    adminHttp = require('http').Server(cAdminApp);
    return adminHttp.listen(server.config.adminPort, (function() {
      return console.log('admin listening on *:' + server.config.adminPort);
    }));
  };

}).call(this);

//# sourceMappingURL=cAdminApp.js.map
