// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(chatApp, db) {
    var adminBasePath, adminHttp, cAdminApp;
    cAdminApp = chatApp.express();
    cAdminApp.use(chatApp.bodyParser.urlencoded({
      extended: true
    }));
    adminBasePath = chatApp.path.normalize(chatApp.config.appFolder + '/../../admin');
    chatApp.initSession(cAdminApp);
    cAdminApp.use(chatApp.express["static"](adminBasePath + '/public'));
    cAdminApp.set('view engine', 'ejs');
    cAdminApp.set('views', adminBasePath + '/views');
    cAdminApp.engine('html', require('ejs').renderFile);
    cAdminApp.get('/auth', function(req, res) {
      return res.render('auth.html', {
        error: null
      });
    });
    cAdminApp.post('/auth', function(req, res) {
      if (!req.body.password) {
        res.render('auth.html', {
          error: 'Password required'
        });
        return;
      }
      if (req.body.password !== chatApp.config.adminPassword) {
        res.render('auth.html', {
          error: 'Password required'
        });
        return;
      }
      req.session.admin = true;
      return res.redirect('/');
    });
    cAdminApp.get('/logout', function(req, res) {
      req.session.admin = false;
      return res.redirect('/auth');
    });
    cAdminApp.use('/admin', function(req, res, next) {
      if (!req.session.admin) {
        res.redirect('/auth');
        return;
      }
      return next();
    });
    cAdminApp.get('/', function(req, res) {
      return res.redirect('/admin');
    });
    cAdminApp.get('/admin', function(req, res) {
      return res.render('index.html', {
        apiUri: chatApp.config.host + ':' + chatApp.config.port,
        adminPassword: chatApp.config.adminPassword
      });
    });
    require('./routes/admin/users')(cAdminApp, db);
    require('./routes/admin/stat')(cAdminApp, db);
    require('./routes/admin/logs')(cAdminApp, db);
    adminHttp = require('http').Server(cAdminApp);
    return adminHttp.listen(chatApp.config.adminPort, (function() {
      return console.log('admin listening on *:' + chatApp.config.adminPort);
    }));
  };

}).call(this);

//# sourceMappingURL=cAdminApp.js.map
