// Generated by CoffeeScript 1.12.0
(function() {
  var SocketEventWrapper;

  SocketEventWrapper = (function() {
    function SocketEventWrapper(server, socket) {
      this.server = server;
      this.socket = socket;
    }

    SocketEventWrapper.prototype.event = function(data) {
      this.socket.emit('event', data);
      return this.server.db.collection('logs').insertOne({
        dt: new Date(),
        url: data.type,
        code: 200,
        body: JSON.stringify(data),
        socket: true
      });
    };

    return SocketEventWrapper;

  })();

  module.exports = SocketEventWrapper;

}).call(this);

//# sourceMappingURL=SocketEventWrapper.js.map
