// Generated by CoffeeScript 1.11.1
(function() {
  var SocketChatEventEmitter;

  SocketChatEventEmitter = (function() {
    function SocketChatEventEmitter(server, chatId1) {
      this.server = server;
      this.chatId = chatId1;
    }

    SocketChatEventEmitter.prototype.getChatOnlineClients = function(chatId) {
      var chatClients;
      chatClients = this.server.io.sockets.adapter.rooms[chatId];
      if (!chatClients) {
        return false;
      }
      if (chatClients.sockets.length === 0) {
        return false;
      }
      return chatClients;
    };

    SocketChatEventEmitter.prototype.emit = function(type, data) {
      var clients, onlineUserId, onlineUserSockets, results, socket, socketId;
      clients = this.getChatOnlineClients(this.chatId);
      if (clients === false) {
        return;
      }
      onlineUserSockets = {};
      for (socketId in clients.sockets) {
        socket = this.server.io.sockets.connected[socketId];
        onlineUserSockets[socket.userId] = socket;
      }
      data = Object.assign({
        type: type
      }, data);
      results = [];
      for (onlineUserId in onlineUserSockets) {
        results.push(onlineUserSockets[onlineUserId].emit('event', data));
      }
      return results;
    };

    return SocketChatEventEmitter;

  })();

  module.exports = SocketChatEventEmitter;

}).call(this);

//# sourceMappingURL=SocketChatEventEmitter.js.map
