// Generated by CoffeeScript 1.11.1
(function() {
  var UserMessage;

  UserMessage = (function() {
    function UserMessage(db, userId) {
      this.db = db;
      this.userId = userId;
    }

    send;

    UserMessage.prototype.getUnseen = function(chatId, callback) {
      return this.db.collection('messageStatuses').find({
        ownUserId: '' + this.userId,
        chatId: '' + data.chatId,
        viewed: false
      }, {
        messageId: 1
      }).toArray(function(err, messageIds) {
        return console.log(messageIds);
      });
    };

    return UserMessage;

  })();

}).call(this);

//# sourceMappingURL=UserMessage.js.map
