// Generated by CoffeeScript 1.11.1
(function() {
  var ChatApp;

  ChatApp = (function() {
    function ChatApp(config) {
      var app, assert, bodyParser, express, http, io, jwt, mongoClient, mongodb, path, url;
      this.config = config;
      express = require('express');
      app = express();
      bodyParser = require('body-parser');
      path = require('path');
      app.use(bodyParser.urlencoded({
        extended: true
      }));
      app.set('view engine', 'jade');
      app.use(express["static"](path.join(__dirname, 'public')));
      http = require('http').Server(app);
      io = require('socket.io')(http);
      url = 'mongodb://localhost:27017/chat';
      jwt = require('jsonwebtoken');
      mongodb = require('mongodb');
      mongoClient = mongodb.MongoClient;
      assert = require('assert');
    }

    return ChatApp;

  })();

}).call(this);

//# sourceMappingURL=ChatApp.js.map
