// Generated by CoffeeScript 1.11.1
(function() {
  var Server;

  Server = (function() {
    function Server(config, app, db, io, jwt) {
      this.config = config;
      this.app = app;
      this.db = db;
      this.io = io;
      this.jwt = jwt;
      require('./routes/api/login')(this);
      require('./routes/api/user')(this);
      require('./routes/api/contacts')(this);
      require('./routes/api/message')(this);
      require('./routes/api/chat')(this);
      require('./routes/admin/login')(this);
      require('./routes/admin/users')(this);
      require('./routes/admin/contacts')(this);
      require('./routes/debug')(this);
      require('./socket')(this);
    }

    Server.prototype.tokenReq = function(req, res, resCallback) {
      return this.jwt.verify(req.query.token, this.config.jwtSecret, function(err, decoded) {
        if (!err) {
          return resCallback(res, decoded);
        } else {
          return res.send(err);
        }
      });
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);

//# sourceMappingURL=Server.js.map
