// Generated by CoffeeScript 1.11.1
(function() {
  var MessageActions, SocketMessageActions;

  MessageActions = require('./MessageActions');

  SocketMessageActions = (function() {
    function SocketMessageActions(server) {
      this.server = server;
      this.server.event.on('newMessage', this.newMessageEvent.bind(this));
    }

    SocketMessageActions.prototype.newMessageEvent = function(message) {
      var clients, onlineUserIds, socket, socketId;
      clients = this.server.io.sockets.adapter.rooms[message.chatId];
      if (!clients) {
        return;
      }
      if (clients.sockets.length === 0) {
        return;
      }
      onlineUserIds = {};
      for (socketId in clients.sockets) {
        socket = this.server.io.sockets.connected[socketId];
        onlineUserIds[socket.userId] = 1;
      }
      return new MessageActions(this.server.db).getUserMessages(message, (function(userMessages) {
        var onlineMessageStatusIds, onlineUserId, results, userMessage;
        console.log(userMessages);
        onlineMessageStatusIds = [];
        for (userMessage in userMessages) {
          if (onlineUserIds[userMessage.ownUserId]) {
            onlineMessageStatusIds.push(userMessage._id);
          }
        }
        this.server.db.collection('messageStatuses').update({
          _id: {
            $in: onlineMessageStatusIds
          }
        }, {
          delivered: true
        });
        console.log(onlineUserIds);
        results = [];
        for (onlineUserId in onlineUserIds) {
          results.push(socket.emit('event', {
            type: 'newMessage',
            message: userMessages[onlineUserId]
          }));
        }
        return results;
      }).bind(this));
    };

    return SocketMessageActions;

  })();

  module.exports = SocketMessageActions;

}).call(this);

//# sourceMappingURL=SocketMessageActions.js.map
