// Generated by CoffeeScript 1.11.1
(function() {
  module.exports(function(server) {
    var getSize;
    getSize = require('get-folder-size');
    return setInterval((function() {
      return getSize(this.config.appFolder + '/public/uploads', (function(err, uploadsSize) {
        return this.db.stats((function(err, dbStat) {
          return this.db.collection('stat').insert({
            time: new Date().getTime(),
            memory: process.memoryUsage().rss,
            cpu: process.cpuUsage().user,
            dbSize: dbStat.dataSize,
            uploadsSize: uploadsSize
          });
        }).bind(this));
      }).bind(this));
    }).bind(this), 60000);
  });

}).call(this);

//# sourceMappingURL=stat.js.map
