// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(app, db) {
    app.get('/admin/stat', function(req, res) {
      return res.render('admin/stat');
    });
    return app.get('/admin/stat/data', function(req, res) {
      return require('../../stat').adminResultHandler(db, req, res);
    });
  };

}).call(this);

//# sourceMappingURL=stat.js.map
