// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(server) {
    server.app.get('/admin/stat', function(req, res) {
      return res.render('admin/stat');
    });
    return server.app.get('/admin/stat/data', function(req, res) {
      return require('../../stat').adminResultHandler(server, req, res);
    });
  };

}).call(this);

//# sourceMappingURL=stat.js.map
